/*
    Our routes mapping
 */

export enum BOOTSTRAP_ROUTES {
  FEATURE_BOOTSTRAP = 'FEATURE_BOOTSTRAP',
}

export enum MOVIE_ROUTES {
  FEATURE_MOVIE_LIST = 'FEATURE_MOVIE_LIST',
  FEATURE_MOVIE_DETAILS = 'FEATURE_MOVIE_DETAILS',
  FEATURE_EDIT_NOTE = 'FEATURE_EDIT_NOTE',
}

export const ROUTES = {
  BOOTSTRAP: BOOTSTRAP_ROUTES,
  MOVIE: MOVIE_ROUTES,
};
